T : 4
tau : 8
alpha : 8
beta : 8

backbone : 'ResNet-50'
trainDataPath : /home/woo/Desktop/job/project/AbnormalBehaviorDetection_System/AI/SlowFast/datasets/train
valDataPath : /home/woo/Desktop/job/project/AbnormalBehaviorDetection_System/AI/SlowFast/datasets/val
trainMetaInfoFile : /home/woo/Desktop/job/project/AbnormalBehaviorDetection_System/AI/SlowFast/slowfast/data/meta_info/meta_info_train.txt
valMetaInfoFile : /home/woo/Desktop/job/project/AbnormalBehaviorDetection_System/AI/SlowFast/slowfast/data/meta_info/meta_info_val.txt

ResNet-50 : {
  middleDim : [0, 0, 64, 128, 256, 512],
  outputDim : [0, 64, 256, 512, 1024, 2048],
  stageBlocks : [0, 0, 3, 4, 6, 3]
}
ResNet-101 : {
  middleDim : [0, 0, 64, 128, 256, 512],
  outputDim : [0, 64, 256, 512, 1024, 2048],
  stageBlocks : [0, 0, 3, 4, 23, 3]
}

numGpus : 1
shuffle : True
batchSize : 8
numClasses : 4
numWorker : 4
iterations : 200000
storeNumber : 1000