T : 4
tau : 8
alpha : 8
beta : 8

backbone : 'ResNet-50'
trainDataPath : '/Users/woo/Desktop/woo/project/AbnormalBehaviorDetection_System/AI/datasets/train'
valDataPath : '/Users/woo/Desktop/woo/project/AbnormalBehaviorDetection_System/AI/datasets/val'
trainMetaInfoFile : '/Users/woo/Desktop/woo/project/AbnormalBehaviorDetection_System/AI/SlowFast/slowfast/data/meta_info/meta_info_train.txt'
valMetaInfoFile : '/Users/woo/Desktop/woo/project/AbnormalBehaviorDetection_System/AI/SlowFast/slowfast/data/meta_info/meta_info_val.txt'

ResNet-50 : {
  middleDim : [0, 0, 64, 128, 256, 512],
  outputDim : [0, 64, 256, 512, 1024, 2048],
  stageBlocks : [0, 0, 3, 4, 6, 3]
}
ResNet-101 : {
  middleDim : [0, 0, 64, 128, 256, 512],
  outputDim : [0, 64, 256, 512, 1024, 2048],
  stageBlocks : [0, 0, 3, 4, 23, 3]
}

numGpus : 0
shuffle : True
batchSize : 2
numClasses : 3
numWorker : 1
iterations : 8