name : 'train'
T : 4
tau : 8
alpha : 8
beta : 8

backbone : 'ResNet-50'
# trainDataPath : /home/woo/Desktop/job/project/AbnormalBehaviorDetection_System/AI/SlowFast/datasets/train
# valDataPath : /home/woo/Desktop/job/project/AbnormalBehaviorDetection_System/AI/SlowFast/datasets/val
# trainMetaInfoFile : /home/woo/Desktop/job/project/AbnormalBehaviorDetection_System/AI/SlowFast/slowfast/data/meta_info/meta_info_train.txt
# valMetaInfoFile : /home/woo/Desktop/job/project/AbnormalBehaviorDetection_System/AI/SlowFast/slowfast/data/meta_info/meta_info_val.txt

# Mac_TrainDataPath : /Users/woo/Desktop/woo/project/AbnormalBehaviorDetection_System/AI/datasets/train
# Mac_ValDataPath : /Users/woo/Desktop/woo/project/AbnormalBehaviorDetection_System/AI/datasets/val
# Mac_TrainMetaInfoFile : /Users/woo/Desktop/woo/project/AbnormalBehaviorDetection_System/AI/SlowFast/slowfast/data/meta_info/meta_info_train.txt
# Mac_ValMetaInfoFile : /Users/woo/Desktop/woo/project/AbnormalBehaviorDetection_System/AI/SlowFast/slowfast/data/meta_info/meta_info_val.txt
Mac_trainDataPath : './datasets/train'
Mac_valDataPath : './datasets/val'
Mac_trainMetaInfoFile : './slowfast/data/meta_info/mac_meta_info_train.txt'
Mac_valMetaInfoFile : './slowfast/data/meta_info/mac_meta_info_val.txt'

Ubuntu_trainDataPath : './datasets/train'
Ubuntu_valDataPath : './datasets/val'
Ubuntu_trainMetaInfoFile : './slowfast/data/meta_info/meta_info_train.txt'
Ubuntu_valMetaInfoFile : './slowfast/data/meta_info/meta_info_val.txt'

pretrainedPath : '/home/woo/Desktop/job/project/AbnormalBehaviorDetection_System/AI/SlowFast/pretrained/best/epoch_50.pth'

ResNet-50 : {
  middleDim : [0, 0, 64, 128, 256, 512],
  outputDim : [0, 64, 256, 512, 1024, 2048],
  stageBlocks : [0, 0, 3, 4, 6, 3]
}
ResNet-101 : {
  middleDim : [0, 0, 64, 128, 256, 512],
  outputDim : [0, 64, 256, 512, 1024, 2048],
  stageBlocks : [0, 0, 3, 4, 23, 3]
}

numGpus : 1
shuffle : True
batchSize : 1
numClasses : 6
numWorker : 4
iterations : 100000
storeNumber : 10
lr : 0.01

## YOLO Option
inputSize : [640, 640]
confThres : 0.25  # confidence threshold
iouThres : 0.45  # NMS IOU threshold
maxDet : 8
# yoloPretrained : '/Users/woo/Desktop/woo/project/AbnormalBehaviorDetection_System/AI/SlowFast/pretrained/yolo_pretrained/yolov5s.pt'
yoloPretrained : '/home/woo/Desktop/job/project/AbnormalBehaviorDetection_System/AI/SlowFast/slowfast/yolov5m.pt'